name: Deploy on Production
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  deploy:
    environment: master
    runs-on: ubuntu-latest
    steps:
    - name: Pull code on server and restart services
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
        debug: ${{ secrets.DEBUG }}
        script: |
          cd /home/zeeshan/share.moviepediafilms.com
          /usr/bin/git pull
          /home/zeeshan/.local/bin/pipenv clean
          /home/zeeshan/.local/bin/pipenv sync
          sudo /usr/sbin/service share.moviepediafilms restart
